package com.thrivent.aws.dynamodb;

import dagger.Module;
import dagger.Provides;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.internal.client.ExtensionResolver;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

import javax.inject.Singleton;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.URI;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Stream;

@Module
public class DynamoDbLocalModule {
    private static final int DEFAULT_PORT = 4566;
    private static final int PORT;

    static {
        int port = 0;
        try (final ServerSocket serverSocket = new ServerSocket(0)) {
            port = serverSocket.getLocalPort();
        } catch (IOException ignored) {
        }
        PORT = port > 0 ? port : DEFAULT_PORT;
    }

    @Provides
    @Singleton
    DynamoDbClient provideDynamoDbClient() {
        final String endpoint = String.format("http://localhost:%d", PORT);

        return DynamoDbClient.builder()
                .endpointOverride(URI.create(endpoint))
                .region(Region.US_EAST_1)
                .build();
    }

    @Provides
    @Singleton
    public DynamoDbEnhancedClient provideDynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
        LinkedList list = new LinkedList<>();
        final List<DynamoDbEnhancedClientExtension> extensions = Stream.concat(
                ExtensionResolver.defaultExtensions().stream(),
                Stream.of(AutoGeneratedTimestampRecordExtension.create())).toList();
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(dynamoDbClient)
                .extensions(extensions)
                .build();
    }

    @Provides
    @Singleton
    DynamoDbLocal provideDynamoDbLocal() {
        return DynamoDbLocal.create(PORT);
    }
}
